import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Sparkles, ThumbsUp, ThumbsDown } from "lucide-react";
import { predictRecommendation, RecommendationResult } from "@/utils/sentimentAnalysis";
import { fetchProductOptions, submitReview } from "@/lib/api";
import { ProductOption } from "@/types/clothing";
import { toast } from "sonner";

const CreateReview = () => {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [searchParams] = useSearchParams();
  const [searchQuery, setSearchQuery] = useState("");

  const preselectedItemId = searchParams.get("itemId");
  const [selectedItemId, setSelectedItemId] = useState<string>(preselectedItemId || "");
  const [title, setTitle] = useState("");
  const [reviewText, setReviewText] = useState("");
  const [rating, setRating] = useState<string>("");
  const [age, setAge] = useState<string>("");
  const [predictedRecommendation, setPredictedRecommendation] = useState<0 | 1 | null>(null);
  const [predictionConfidence, setPredictionConfidence] = useState<number | null>(null);
  const [predictionSource, setPredictionSource] = useState<RecommendationResult["source"] | null>(null);
  const [manualRecommendation, setManualRecommendation] = useState<0 | 1 | null>(null);
  const [isPredicting, setIsPredicting] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const { data: productOptions = [], isLoading: isLoadingOptions } = useQuery({
    queryKey: ["product-options"],
    queryFn: fetchProductOptions,
  });

  useEffect(() => {
    if (preselectedItemId && productOptions.length > 0) {
      const exists = productOptions.some((option) => option.id === preselectedItemId);
      if (exists) {
        setSelectedItemId(preselectedItemId);
      }
    }
  }, [preselectedItemId, productOptions]);

  useEffect(() => {
    setPredictedRecommendation(null);
    setManualRecommendation(null);
    setPredictionConfidence(null);
    setPredictionSource(null);
  }, [reviewText, rating]);

  const selectedItem: ProductOption | undefined = productOptions.find(
    (option) => option.id === selectedItemId,
  );

  const handlePredict = async () => {
    if (!reviewText || !rating) {
      toast.error("Please enter review text and rating first");
      return;
    }

    setIsPredicting(true);

    try {
      const result = await predictRecommendation(reviewText, Number(rating));
      setPredictedRecommendation(result.prediction);
      setManualRecommendation(result.prediction);
      setPredictionConfidence(result.confidence ?? null);
      setPredictionSource(result.source);

      toast.success(
        `Recommendation: ${result.prediction === 1 ? "Recommended" : "Not Recommended"}`,
        {
          description:
            result.source === "backend"
              ? "Prediction generated by the FastText + Logistic Regression model"
              : "Prediction generated using offline fallback heuristics",
        }
      );
    } catch (error) {
      console.error("Failed to generate prediction", error);
      toast.error("Unable to generate a recommendation", {
        description: "Please try again or adjust your review text."
      });
    } finally {
      setIsPredicting(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!selectedItemId || !title || !reviewText || !rating) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (manualRecommendation === null) {
      toast.error("Please generate a recommendation prediction first");
      return;
    }

    setIsSubmitting(true);

    try {
      await submitReview({
        productId: selectedItemId,
        title,
        reviewText,
        rating: Number(rating),
        recommended: manualRecommendation,
        age: age ? Number(age) : undefined,
      });

      toast.success("Review submitted successfully!", {
        description: "Your review has been added and is now visible to other shoppers",
      });

      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["products"] }),
        queryClient.invalidateQueries({ queryKey: ["product", selectedItemId] }),
        queryClient.invalidateQueries({ queryKey: ["product-options"] }),
      ]);

      navigate(`/product/${selectedItemId}`);
    } catch (error) {
      console.error("Failed to submit review", error);
      toast.error("Unable to submit review", {
        description: error instanceof Error ? error.message : "Please try again later.",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar searchQuery={searchQuery} onSearchChange={setSearchQuery} />

      <div className="container mx-auto px-4 py-8">
        <Button
          variant="ghost"
          className="mb-6"
          onClick={() => navigate("/")}
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Button>

        <div className="max-w-2xl mx-auto">
          <Card>
            <CardHeader>
              <CardTitle className="text-3xl">Write a Review</CardTitle>
              <CardDescription>
                Share your experience with this product to help other shoppers
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="item">Select Item *</Label>
                  <Select
                    value={selectedItemId}
                    onValueChange={setSelectedItemId}
                    disabled={isLoadingOptions}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder={isLoadingOptions ? "Loading items..." : "Choose a clothing item"} />
                    </SelectTrigger>
                    <SelectContent>
                      {productOptions.map((item) => (
                        <SelectItem key={item.id} value={item.id}>
                          {item.title} - {item.category}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {selectedItem && (
                    <div className="flex items-center gap-3 p-3 bg-muted rounded-md mt-2">
                      <img
                        src={selectedItem.imageUrl}
                        alt={selectedItem.title}
                        className="h-16 w-16 object-cover rounded"
                      />
                      <div>
                        <p className="font-semibold">{selectedItem.title}</p>
                        <Badge variant="secondary">{selectedItem.category}</Badge>
                      </div>
                    </div>
                  )}
                </div>

                <div className="space-y-2">
                  <Label htmlFor="title">Review Title *</Label>
                  <Input
                    id="title"
                    placeholder="Sum up your experience in one line"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="review">Review Text *</Label>
                  <Textarea
                    id="review"
                    placeholder="Tell us about your experience with this item..."
                    rows={6}
                    value={reviewText}
                    onChange={(e) => setReviewText(e.target.value)}
                    required
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="rating">Rating *</Label>
                    <Select value={rating} onValueChange={setRating}>
                      <SelectTrigger>
                        <SelectValue placeholder="Select rating" />
                      </SelectTrigger>
                      <SelectContent>
                        {[5, 4, 3, 2, 1].map((r) => (
                          <SelectItem key={r} value={r.toString()}>
                            {r} Star{r !== 1 ? "s" : ""}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="age">Age (optional)</Label>
                    <Input
                      id="age"
                      type="number"
                      min={0}
                      placeholder="Enter your age"
                      value={age}
                      onChange={(e) => setAge(e.target.value)}
                    />
                  </div>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Recommendation</Label>
                      <p className="text-sm text-muted-foreground">
                        Generate an AI-powered recommendation to pre-fill your response
                      </p>
                    </div>
                    <Button type="button" variant="secondary" onClick={handlePredict} disabled={isPredicting}>
                      <Sparkles className="mr-2 h-4 w-4" />
                      {isPredicting ? "Generating..." : "Predict"}
                    </Button>
                  </div>

                  {(predictedRecommendation !== null || manualRecommendation !== null) && (
                    <div className="grid grid-cols-2 gap-4">
                      <Button
                        type="button"
                        variant={manualRecommendation === 1 ? "default" : "outline"}
                        onClick={() => setManualRecommendation(1)}
                      >
                        <ThumbsUp className="mr-2 h-4 w-4" /> Recommended
                      </Button>
                      <Button
                        type="button"
                        variant={manualRecommendation === 0 ? "default" : "outline"}
                        onClick={() => setManualRecommendation(0)}
                      >
                        <ThumbsDown className="mr-2 h-4 w-4" /> Not Recommended
                      </Button>
                    </div>
                  )}

                  {predictionConfidence !== null && predictionSource && (
                    <p className="text-sm text-muted-foreground">
                      Confidence: {(predictionConfidence * 100).toFixed(1)}% ({predictionSource === "backend" ? "Model" : "Fallback"} prediction)
                    </p>
                  )}
                </div>

                <Button type="submit" className="w-full" disabled={isSubmitting}>
                  {isSubmitting ? "Submitting..." : "Submit Review"}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default CreateReview;
